version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: bstar-website-db
    hostname: db
    env_file:
      - .env
    volumes:
      - ./.data/db:/var/lib/postgresql/data
      - ./pg:/var/tmp/pg
    ports:
      - 5442:5432
    healthcheck:
      test: pg_isready -U postgres || exit 1
    stop_grace_period: 1m

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
